### PR TITLE
Customize timestamp format

### PR DESCRIPTION
**Pull request by chunyenHuang**
#119 

Timestamp is good for index and query, but it's not really readable from database. In this PR, I provide the ability to overwrite the timestamp with Date String.

### CODE REVIEW

**Comment by chunyenHuang** [comment]
cool, so based on the conversation in https://github.com/dynamoosejs/dynamoose/issues/382#issuecomment-405783548

If I understand correctly, the end goal will be 
```
{
    timestamps: {
        createdAt: {
            rangeKey: true, // this should add the index as well
            name: "createdAt",
            type: String,
            default: function (){ 
                return new Date().toLocaleString();
            }
        },
        updatedAt: true
    }
}
```
However, I think this just make the `timestamp` away from the schema. What about we just allow the user to overwrite the timestamp format through schema?

for example, 
```
    new Schema({
         started_at: {
            rangeKey: true, // this should add the index as well
            type: String,
            default: function (){ 
                return new Date().toLocaleString();
            }
        },
    }, {
        timestamp: {
            createdAt: 'started_at'
        }
    });
```

In `Schema.js`
```
    obj[createdAt] = obj[createdAt] || {};
    obj[createdAt].type = obj[createdAt].type || timestampType;
    obj[createdAt].default = obj[createdAt].default || timestampDefaultFunciton;
```

**Comment by fishcharlie** [comment]
@chunyenHuang Sure that works. So long as in the schema none of the properties are required. For example if you don't set a type or default, it should just work as normal.

Maybe use a spread operator to set the default values and spread over the user defined options?

Only other concern is I think other parts of the application rely on the timestamps, so ensuring those work as expected is important too I think.

**Comment by dolsem** [comment]
@chunyenHuang I'm very much interested in this as well, cause I'm getting the same error when I try to get an item from the database. It seems like what's failing is the test case you created for your feature/bug fix. After a quick look at it, might I suggest that you move your test code inside the already existing test 'Schema with timestamps options that are rangeKey'? Unless I'm missing something, I think it would make sense for this test to fail, because currently having timestamp as a rangeKey doesn't properly work. I hope you can get this pulled soon!

**Comment by fishcharlie** [comment]
Closing this due to no recent activity. If this is still a problem or you have questions please feel free to comment again and we can try to help further.

**Comment by mgwidmann** [comment]
Is this feature possible? I can't seem to find it in the documentation or issues anywhere...

**Comment by fishcharlie** [comment]
@mgwidmann This isn't implemented currently. Feel free to create a PR. You could also do this manually as part of your schema. The `Date` type in Dynamoose has a few different options for how to store the underlying date. Would be cool to add more options to that in the future, but haven't gotten around to that either yet.

**Pull request closed without merging**
