### PR TITLE
originalItem function returns a strongly typed value

### PR DESCRIPTION
**Pull request by qisaw**
### Summary:
Even if you explicitly pass types when creating models, when you call the `originalItem` function, you lose types.
This PR ensures that the originalItem function returns the `ModelData` so that we don't lose typing

#### Model
```
const myModel = dynamoose.model<ModelType, KeyType>("model", schema, { ... });
```

#### General
```
const item = await ProductDBModel.get() // type ModelSchema<ModelType>
if (product) {
  item.getOriginalItem() // type ModelType instead of generic Object
}
```

### GitHub linked issue:

#---

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoosejs/dynamoose/blob/master/LICENSE.txt)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by fishcharlie** [comment]
@qisaw This PR doesn't follow the Git commit guidelines for this project. @hweeks should be able to give info about how to fix.

**Comment by kibertoad** [comment]
@fishcharlie Judging by the fact that this PR remains untouched since March, doesn't super-strict policy result in losing valuable contributions?..

**Comment by hweeks** [comment]
hey @kibertoad, the reason we need to follow a commit format is that we’ve automated release and versioning completely. i’d argue completely automated releases outweigh any complexity in creating the commit, especially when we’ve added a whole lot of tools for you when developing that explain and help format this stuff.

**Comment by kibertoad** [comment]
@hweeks It depends. Based on my experience in maintaining `knex`, which is a fairly large and active project, I would say that amount of time I spend manually updating changelog and doing the actual release is completely negligible compared to amount of time that would be needed to reimplement some of the PRs that members of the community are sending in. YMMV, obviously, and if you are seeing only an insignificant amount of valuable PRs that get rejected merely on the basis of not following conventions, then investing into all that tooling obviously paid off :D.

**Comment by hweeks** [comment]
@kibertoad but he only needs to add a single word lol

**Comment by kibertoad** [comment]
@hweeks That was more a question about project philosophy, not about this specific PR :D. I was just curious if after applying this approach for some time you feel that it is helping more than hurting.

**Comment by hweeks** [comment]
@kibertoad honestly yeah. it’s a low barrier to entry and generally i feel that it has increased submission quality over anything else

**Comment by qisaw** [comment]
Lol sorry guys, I just saw the comments on this thread.

I’ll update this tonight. Am looking at my phone atm

**Pull request closed without merging**
