### PR TITLE
DynamoDB Document Client/DAX Support

### LINKED ISSUE #212: Any plan to integrate with DAX?
https://aws.amazon.com/dynamodb/dax/

### PR DESCRIPTION
**Pull request by fishcharlie**
This PR adds support to set the DynamoDB document client, which can be used to use DAX with Dynamoose.

Close #212, #261.

### CODE REVIEW

**Comment by sirgalleto** [comment]
What is missing for the approval? May I help you with something?

**Comment by fishcharlie** [comment]
@sirgalleto A second code review would be good. I'm pretty sure it's good, but would love some feedback if you think it's good or not or needs more adjustments.

Besides that I'm waiting for @brandongoode to reply to my emails. Once that happens I will finish up version 0.9, which this PR will be included in.

**Comment by sirgalleto** [comment]
I see. Currently, I was intensely looking into the documentation for this exact implementation, a way to set the client to use DAX which is the current blocker of my team and the reason for choosing another ORM as Dynogels. If I'd know the new version release plan, I'd have enough arguments for still using Dynamoose. 

The documentation is added correctly, tests increasing the coverage and clean implementation. From my view, this is a high leverage PR due to the straightforward implementation to use DAX. 

Thanks for this great contribution 👍

**Comment by fishcharlie** [comment]
@sirgalleto I would love to be able to give a better timeframe for when this will be released in an NPM version. But if you asked me on April 3rd when I thought this would be available in a release version I would have for sure said before today. I'm hoping to get it integrated soon tho!!

**Comment by sirgalleto** [comment]
Thanks for your notification, I'll keep watching this PR 💯

**Comment by sirgalleto** [comment]
👏

**Comment by zhenyulin** [comment]
is there a timeline when this would be released?

**Comment by fishcharlie** [comment]
@zhenyulin This is part of version 1.0 (#365). Once #376 gets merged in we can release version 1.0. Currently we have some failing tests on PR #376. Any help solving that would be much appreciated and help version 1.0 be released quicker.

**Comment by Nikhil2508** [comment]
Has DAX support been integrated? If yes, can someone please post the link to necessary documentation/example. Thanks

**Comment by fishcharlie** [comment]
@Nikhil2508 Yes, it has been released as of Dynamoose version 1.0. This is the PR that has all the changes in it, including documentation changes. You can also find the documentation on the [Dynamoose website](https://dynamoosejs.com/api#dynamoosesetdocumentclientdocumentclient).

**Comment by ThienNDDi** [comment]
@fishcharlie I using dynamoose V3.
I can not find setDocumentClient variable.
Is it changed to Instance?
Thank very much.

**Comment by fishcharlie** [comment]
@ThienNDDi This is a 6 year old PR. Lot has changed since then. There is an active discussion in the Dynamoose Slack about this. There are a few complications with circular references and lack of promise support on AWS's end. You can follow along more there.

**Comment by ThienNDDi** [comment]
@fishcharlie Can you provide me with more detail? I checked slack but it's requiring i have to upgrade plans.
So if i wanna use DAX with dynamoose, have you any idea?

**Comment by fishcharlie** [comment]
@ThienNDDi There shouldn't be any need to upgrade. I don't think DAX is currently working in Dynamoose is the short answer. Hopefully we can get it working soon. Stay tuned.

**Comment by ThienNDDi** [comment]
@fishcharlie Can i use your code in this PR and will DAX work? If it doesn't work, i have to change every thing feature from dynamoose to DAX. Am i right?

**Pull request merged**
