### PR TITLE
Async Schema Methods

### LINKED ISSUE #313: Async Set, validate
It would be nice to have async / await or Promise resolve before writing to database, this save time to validate existing or write password

### PR DESCRIPTION
**Pull request by fishcharlie**
### Summary:

This PR adds support for async schema methods.

**DONE:**

- `validate` *
- `set` *
- `get` *
- `default`
- `toDynamo` *
- `fromDynamo` *

`*` indicates that it works with passing in an object, with `isAsync` for callback support.

#### Schema
```js
new dynamoose.Schema({
  id: Number,
  name: {
    type: String,
    validate: function (val) {
      return new Promise(function(resolve, reject) {
        setTimeout(() => resolve(val.length >= 5), 1000);
      });
    }
  }
})
```

### GitHub linked issue:

Close #313 

### Type (select 1):
- [ ] Bug fix
- [x] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement
- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [ ] Yes
- [x] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I have run `npm test` from the root of the project directory to ensure all tests continue to pass
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoosejs/dynamoose/blob/master/LICENSE.txt)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have confirmed that all my code changes are indented properly using 2 spaces
- [x] I have filled out all fields above

---

cc/ @yoitsro

### CODE REVIEW

**Comment by fishcharlie** [comment]
@yoitsro Wanna take a look at this PR and let me know what you think?

**Comment by fishcharlie** [comment]
Still waiting on @yoitsro to review this PR before merging to see if it's compatible with the Mongoose API and will allow integration with https://github.com/yoitsro/joigoose.

If we don't hear back somewhat soon I will be merging this PR in, and any further changes will probably require a breaking change (vX.0.0).

---

Also requested review from @brandongoode to review this if he gets a chance before we merge it in to give any thoughts he might have.

**Comment by yoitsro** [comment]
Hey @fishcharlie. Sorry about the delay on this.

According to https://github.com/Automattic/mongoose/blob/50b9daefff0dd508ab225c020133ef3d265f123d/test/docs/validation.test.js#L234 (and your documentation in fact!), I shouldn't be setting the `isAsync` flag on promise based validators. As a result, I've just made this change and bumped it on version 4.0.3.

I've also just tested against dynamoose, and it looks good!

**Comment by fishcharlie** [comment]
@yoitsro Awesome! This will get merged in soon and will be released in the next Dynamoose version.

**Pull request merged**
