### PR TITLE
Emit 'batchPut' and 'update' plugin events

### PR DESCRIPTION
**Pull request by dolsem**
### Summary:
Adds missing batchPut and update events to Plugin API, as mentioned in #325.

### GitHub linked issue:

#565 

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoosejs/dynamoose/blob/master/LICENSE.txt)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by dolsem** [comment]
@fishcharlie I picked not ready to be merged because I might add some tiny changes to `update` event later. That being said, I would like to hear your feedback and would really appreciate this getting reviewed some time soon.

**Comment by fishcharlie** [comment]
@dolsem Quick first pass and this looks really good!!

**Comment by fishcharlie** [comment]
@dolsem Let me know when you are ready for a final review and merge.

**Comment by dolsem** [comment]
@fishcharlie this is finalized now and ready to be merged. Travis is failing because of some unrelated CI configuration issue.

**Comment by repl-sean-heintz** [comment]
Would love to see this get merged. We're planning on using a Dynamoose plugin to enforce tenant-level data isolation within a single table, and without plugin support for all (or nearly all) of the operations it will be hard to effectively achieve that.

**Comment by dolsem** [comment]
Pinging @fishcharlie

**Comment by fishcharlie** [comment]
Not sure why this build is failing. It was failing on another PR as well on Node.js v9 as well.

**Comment by dolsem** [comment]
@fishcharlie Travis's logs say 
```
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module '../pack.js'
```
, while running `npm ci`. Pretty sure this is a CI issue, doesn't have anything to do with the PR itself.

**Comment by fishcharlie** [comment]
@dolsem I got into the beta of GitHub CI. So I’m gonna migrate this repository over to that once I get back from vacation. Hopefully that fixes the issue.

**Pull request merged**
