### PR TITLE
Save Unknown Object Tests

### PR DESCRIPTION
**Pull request by fishcharlie**
### Summary:

This PR adds tests to reproduce the bug in #434.

### GitHub linked issue:
#434 

### Type (select 1):
- [ ] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement
- [x] Test added to report bug (GitHub issue #434 @fishcharlie)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [ ] Yes
- [x] No

### Are all the tests currently passing on this PR? (select 1):
- [ ] Yes
- [x] No

### Other:
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I have run `npm test` from the root of the project directory to ensure all tests continue to pass
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoosejs/dynamoose/blob/master/LICENSE.txt)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have confirmed that all my code changes are indented properly using 2 spaces
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by fishcharlie** [comment]
Another tip for debugging, running `export DEBUG=*` beforehand gives a lot of useful debug information and extra logs related to Dynamoose. Also adding `.only` before the tests is super useful also so you only run the tests you care about.

**Comment by fishcharlie** [comment]
Also I did notice differences between using `objectA: Object` and `objectA: {type: Object}`. I don't know if that is normal or not.

**Comment by fishcharlie** [comment]
So strange that this is now passing... for future reference in case it's needed I think PR #339 might be the cause of this.

**Comment by brandongoode** [comment]
@fishcharlie I've tried several ways to trigger the error too and can't get it to fail.   I agree the test issue is caused by #339.

**Comment by fishcharlie** [comment]
@brandongoode I'm wondering if this is because the data stored in DynamoDB is saved as a string (old version), yet the schema says it's an object, and now it's trying to parse a DynamoDB map.

In #434 I asked @ThomasVictoria to share his raw DynamoDB document.

I still am concerned that #339 is causing problems related to this tho. Maybe at some point you can take a look through the change log of that PR and see if anything stands out?

**Pull request closed without merging**
