### PR TITLE
Always use Array.isArray to check if array

### PR DESCRIPTION
**Pull request by dobrynin**
### Summary:
Change usage of `array instanceOf Array` and `util.isArray(array)` to `Array.isArray(array)`.
My team found this to be an issue when trying to use the `Model.batchPut`. 

### Other information:

- `array instanceof Array` breaks when multiple `Array` globals exist: http://web.mit.edu/jwalden/www/isArray.html

- `util.isArray` is deprecated: https://nodejs.org/api/util.html#util_util_isarray_object

### Type (select 1):
- [x] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I have run `npm test` from the root of the project directory to ensure all tests continue to pass
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoosejs/dynamoose/blob/master/LICENSE.txt)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have confirmed that all my code changes are indented properly using 2 spaces
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by dobrynin** [comment]
Just pushed a test, please take a look @fishcharlie.

**Comment by fishcharlie** [comment]
@dobrynin Looks like there is a merge conflict. Wanna try to solve that?

**Comment by fishcharlie** [comment]
@dobrynin And just to confirm. That test you added, fails without your changes, correct?

**Comment by dobrynin** [comment]
All set. The test fails without these changes. The test is for the specific case that gave us trouble (batchPut)

**Pull request merged**
