### PR TITLE
fix: model.get is calling validate when it should not

### PR DESCRIPTION
**Pull request by Tirke**
re #583

### Is this ready to be merged into Dynamoose? (select 1):
- [ ] Yes
- [x] No

### Other:
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoosejs/dynamoose/blob/master/LICENSE.txt)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by hweeks** [comment]
@fishcharlie any movement on this concept? is there a reason why we need to validate on both put and get?

**Comment by fishcharlie** [comment]
@hweeks Parity with mongoose I think is important in this case. That being said, just from a pure logic standpoint, I'm of the opinion that we should validate in both places. Seems like an extra safe guard in case the data gets updated in DynamoDB directly, without Dynamoose.

If someone wants to actually implement this, feel free. I need to get around to confirming Mongoose behavior. After I confirm that I'll merge it in. Needs to be implemented tho as well.

**Comment by hweeks** [comment]
I believe I sent you the code in Mongoose in slack. Double check that link

**Comment by fishcharlie** [comment]
@hweeks Can’t find it.

**Pull request closed without merging**
