### PR TITLE
fix(regex): allows attributes to have numeric characters

### PR DESCRIPTION
**Pull request by Toolito**
### Summary:

Allows attributes to have numeric characters

### Other information:

Updated the regex to match dot + number instead of just number.

### Type (select 1):
- [x] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement
- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I have ensured the following commands are successful from the root of the project directory
  - [x] `npm test`
  - [x] `npm run lint`
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoosejs/dynamoose/blob/master/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by fishcharlie** [comment]
@Toolito Looks like I was able to merge into your branch. Just take a look at the suggested changes I suggested and then we should be good to go here.

**Comment by Toolito** [comment]
Your changes are good for me.
I don't know why the last check CI is blocking...

**Comment by fishcharlie** [comment]
@Toolito I wanna investigate the `coveralls` status a bit more before merging this. Will for sure get it in for the next beta release tho.

**Comment by fishcharlie** [comment]
@Toolito I apologize for the long wait in merging this. Really wanna figure out why Coveralls isn't working since this isn't something I can test on my own easily. Send an email to their support a week ago and still haven't heard back. Followed up again today, hopefully will get a reply soon.

**Pull request merged**
