### PR TITLE
Version 1.0.0

### PR DESCRIPTION
**Pull request by fishcharlie**
## Version 1.0.0

Dynamoose version 1.0.0 will be released soon. This is a **massive** release, and will also be the first official breaking update to Dynamoose. You can view the details about the release below.

This version officially removes support for Node.js versions below 8.0. Versions below 8.0 _might_ work, but we do not make guarantees. Even if Node.js versions below 8.0 work with Dynamoose 1.0+ we might add features that break support for older Node.js versions _without_ a SEMVER major version release.

The one major thing about the release notes below that is a bit confusing is the fact that `ES6/Future Changes` are in the `Breaking changes` section. That section is directly related to `Requiring Node.js version 8.0 and higher`. Therefor although the breaking change is technically the fact that Node.js versions less than 8.0 won't be supported, they are directly related, therefor they are both in the `Breaking changes` section. In future 1.x we might add more ES6/Future Changes, but those will not be considered breaking changes due to the fact that it will only break if you are running on a Node.js version less than version 8.0.

Please comment or [contact me](https://charlie.fish/contact) if you have any questions about this release.

### 🚨 Breaking changes 🚨

- **[Requiring Node.js version 8.0 and higher](https://github.com/automategreen/dynamoose/pull/366)** #366 
- **[Toggle useDocumentTypes and useNativeBooleans defaults to true](https://github.com/dynamoosejs/dynamoose/pull/376)** #376 
- **[Query.all and Scan.all Delay Seconds to Milliseconds](https://github.com/automategreen/dynamoose/pull/287)** #287 
- **[Fix data corruption when storing binary data](https://github.com/automategreen/dynamoose/pull/386)** #386 

### Major New Features

- **[Adding updateTimestamps option to Model.save](https://github.com/automategreen/dynamoose/pull/317)** #317 
- **[Feature/add enum attribute](https://github.com/automategreen/dynamoose/pull/274)** #274   
- **[`model.originalItem() `](https://github.com/automategreen/dynamoose/pull/338)** #338 

### General

- **[Adding support for saveUnknown being an array](https://github.com/automategreen/dynamoose/pull/333)** #333  
- **[DynamoDB Document Client/DAX Support](https://github.com/automategreen/dynamoose/pull/330)** #330 
- **[Adding better error handling for parsing invalid data from DynamoDB](https://github.com/automategreen/dynamoose/pull/331)** #331 
- **[Adding support for SSESpecification](https://github.com/automategreen/dynamoose/pull/306)** #306 
- **[Adding support for DynamoDB table streams](https://github.com/automategreen/dynamoose/pull/332)** #332 
- **[`Model.getTableReq()`](https://github.com/automategreen/dynamoose/pull/308)** #308 #151 
- **[Static methods are automatically bound with the context of their Model](https://github.com/automategreen/dynamoose/pull/361)** #361 
- **[Recreate dynamo db instance on .local()](https://github.com/automategreen/dynamoose/pull/354)** #354 
- **[added support for specifying the ReturnValues option in update](https://github.com/automategreen/dynamoose/pull/350)** #350 
- **[Expose Model classes to Schema methods](https://github.com/automategreen/dynamoose/pull/400)** #400 #397 
- **[Refactoring custom error code](https://github.com/automategreen/dynamoose/pull/414)** #414
- **[Saying which table is effected by Error](https://github.com/automategreen/dynamoose/pull/356)** #356 
- **[Adding expires returnExpiredItems property](https://github.com/automategreen/dynamoose/pull/426)** #426 
- **[DDB Functions](https://github.com/automategreen/dynamoose/pull/429)** #429 
- **[Updates Expires attribute on Model Updates Option](https://github.com/automategreen/dynamoose/pull/420)** #420 
- ES6/Future Changes
    - **[`let`/`const`](https://github.com/automategreen/dynamoose/pull/410)** #410  
    - **[Removing Lodash](https://github.com/automategreen/dynamoose/pull/411)** #411 
    - **[Removing self = this in favor of arrow functions](https://github.com/automategreen/dynamoose/pull/412)** #412 

### Bug Fixes

- **[Fix saveUnknown throwing errors when value where falsy](https://github.com/automategreen/dynamoose/pull/336)** #336 
- **[Fix scanByRawFilter containing - Select: 'COUNT'](https://github.com/automategreen/dynamoose/pull/341)** #341 
- **[Fix loading document type attributes from DynamoDB when when saveUnknown=true](https://github.com/automategreen/dynamoose/pull/339)** #339 
- **[Fix the ModelError type](https://github.com/automategreen/dynamoose/pull/374)** #374  
- **[Fixes falsy key value for batch get](https://github.com/automategreen/dynamoose/pull/379)** #379
- **[Fix serverSideEncryption option](https://github.com/automategreen/dynamoose/pull/383)** #383 
- **[Using Buffer.from instead of new Buffer](https://github.com/automategreen/dynamoose/pull/413)** #413
- **[Fixing issue with query with multiple indexes](https://github.com/automategreen/dynamoose/pull/344)** #344 #343  
- **[Save unknown update](https://github.com/automategreen/dynamoose/pull/431)** #431 #403   
- **[Fixing typo related to stream options](https://github.com/automategreen/dynamoose/pull/432)** #432 #430 

### Documentation

- **[Improving Model.delete documentation](https://github.com/automategreen/dynamoose/pull/309)** #309 
- **Updated TypeScript types** #358 #357 
- **[Updating typescript documentation for create vs put overwrite default](https://github.com/automategreen/dynamoose/pull/377)** #377 #359
- **[GitHub issue and PR templates](https://github.com/automategreen/dynamoose/pull/394)** #394 #405 
- **[Updating metadata](https://github.com/automategreen/dynamoose/pull/369)** #369 
- **[Change QueryKey and ScanKey type to any](https://github.com/automategreen/dynamoose/pull/419)** #419 

### Other

- **[General project work](https://github.com/automategreen/dynamoose/pull/409)** #409

### CODE REVIEW

**Comment by hassankhan** [comment]
Hi @fishcharlie, the roadmap[ROADMAP.md] says that v1.0 will include ES2015 updates - is that going to be pushed to a future version? Also, will #325 be merged in for v1.0 as well?

**Comment by fishcharlie** [comment]
The last major PR #376 is almost ready to go. There are currently 2 failing tests in that PR that need to be resolved before merging. I haven't had a lot of time to go through and debug it, but any help solving those two tests will help v1.0 be released faster.

Once those two tests are fixed, I'll merge it in, then finalize v1.0 and submit to NPM. Hopefully that will happen soon. Any help with solving those 2 test failures would be much appreciated!!

**Comment by mxhifi** [comment]
Looking forward to this release guys!! 🎉

**Comment by fishcharlie** [comment]
@mxhifi It'll be amazing!! Once #376 gets merged in we'll be able to release. Anything you can do to help with that PR would be much appreciated.

**Comment by fishcharlie** [comment]
Still need to go through and [review all the changes made since last version](https://github.com/dynamoosejs/dynamoose/compare/v0.8.7...master) to verify everything is legit.

**Comment by stewartjarod** [comment]
How can I help get this released?

**Comment by fishcharlie** [comment]
@stewartjarod Honestly just going through [this link](
https://github.com/dynamoosejs/dynamoose/compare/v0.8.7...master) and reviewing all the changes, and doing any testing you can would be super helpful. This is a **massive** update so anything you can do to review things and catch any bugs would be super helpful. Other than that reviewing the open PRs and issues and if you wanna fix any other bugs that would be awesome too.

If you do review that link I posted above please comment here with any findings (positive or negative). 😃 

I'm hoping to finish this up either tonight or this weekend. I was kinda hoping to get #420 in with this release, but looks like that might not happen.

**Comment by fishcharlie** [comment]
Dynamoose version 1.0.0 has officially been released!! Go check it out now on [NPM](https://www.npmjs.com/package/dynamoose), and don't forget to [read the release notes](https://github.com/dynamoosejs/dynamoose/releases/tag/v1.0.0).

Remember, this is a breaking release to Dynamoose, so please especially read the breaking changes section of the release notes so you can update your code and systems to ensure compatibility with the latest version.

Huge thank you to everyone who helped make this release possible!!! 🔥

**Pull request merged**
