### PR TITLE
Semantic release

### PR DESCRIPTION
**Pull request by hweeks**
### Summary:

This should add semantic release and some more helpers around getting commit messages right.

@fishcharlie you're going to have to add your NPM_TOKEN and create a GH_TOKEN for travis to finish this up. 

You could also be proactive and use [the semantic cli](https://github.com/semantic-release/cli) which should make it even easier.

### Type (select 1):
- [ ] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [x] Testing improvement

- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoosejs/dynamoose/blob/master/LICENSE.txt)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by fishcharlie** [comment]
@hweeks Thanks for this! Few questions:

1. What is the process for me releasing a new version? Currently I follow the following steps:
    1. Put release notes in CHANGELOG.md
    2. Merge release PR with bumped version
    3. Pull and checkout master branch
    4. Run `npm publish`
    5. Create Git tag for version
    6. Push to Git
    7. Post release notes under GitHub release
2. What do contributors need to do to ensure their commits are formatted correctly? I didn't see anything really about the correct formatting of commit messages in the CONTRIBUTING.md. Is it just `npm run commit`? If so I think we should make that a LOT more obvious. I think having it that far down in the CONTRIBUTING.md file might cause problems. It's a lot easier to go back and fix tests, or fix linters, but going back and fixing commit messages is more difficult. So I think we need to make sure we make that more clear than tests and lint.

**Comment by hweeks** [comment]
## Release Process

With semantic, all you have to do is merge it to master, have it pass all tests, it will bundle and release the project automatically. That's why it needs your NPM and GIT tokens. It will also create release notes for you automatically.

For the changelog, I don't have anything setup yet, but we can do that if you'd like.

2. The formatting of commits is automated in this scenario, the npm run commit will walk them through doing a commit, or they can use the standard commit pattern as defined by our commit config.

[more info on commit](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)

**Comment by fishcharlie** [comment]
@hweeks 

1. There are times when I want to bundle several PRs together into 1 release. Is there a way we could set it up to have manual releases? Or should we have a `develop` branch that I merge into master when ready for a release?
2. I think we should still use the changelog as well.
3. Can we make the fact that they have to use `npm run commit` or follow that format more obvious in the CONTRIBUTING.md? Right now I feel like it's not obvious enough and will lead to a lot of mistakes.

**Comment by hweeks** [comment]
husky will fail them with why their commit is off when they attempt to make it. I can add more info though. As for the release schedule, if pr commits are correct then it will release minor, major, and patch automatically. If you'd prefer the master develop idea is fine, but this type of automation should be ok. A bunch of small version releases are pretty common.

**Comment by hweeks** [comment]
and they don't have to use npm run commit, any commit of the format:

    <type>(<content>): <what this is>

will pass.

**Comment by fishcharlie** [comment]
@hweeks Fair enough. Let's at least move `npm run commit` to the top of those scripts in the contributing.md, since it'll be one of the most important. Then let's do the changelog thing.

Can you also make sure you have enabled allow commits from collaborators (or whatever it's called) on this PR? After you make the changelog update, I will commit to your branch to add the keys.

**Comment by hweeks** [comment]
keys should only be in travis, don't upload them to the repo ever. to insert private keys into travis you've got to login to travis and make them secret there.

**Comment by fishcharlie** [comment]
@hweeks Pretty sure there is a way to encrypt them locally on my machine, using some type of Travis key. Then upload them to the repo. But they are encrypted. So they should be fine.

**Comment by fishcharlie** [comment]
@hweeks Try pulling the `master` branch into this one. I just committed the encrypted keys to `master`.

**Comment by hweeks** [comment]
i'm not seeing them in master, are you sure?

**Comment by fishcharlie** [comment]
@hweeks Sorry one sec. I pushed to my fork.

**Comment by fishcharlie** [comment]
@hweeks There we go

**Comment by fishcharlie** [comment]
@hweeks Anything else? Or should we try to merge this?

**Comment by hweeks** [comment]
lemme pull your changes, then lemme double check everything over here. 5 mins or so

**Comment by fishcharlie** [comment]
@hweeks Perfect! Keep me posted.

**Comment by hweeks** [comment]
@fishcharlie looking good my dude, let's see if it cuts a release for you automatically

**Comment by fishcharlie** [comment]
@hweeks So how do merge commits work? Since git tends to do those automatically.

**Comment by hweeks** [comment]
they are igonred, as they don't add anything new to the commit in flight

**Comment by fishcharlie** [comment]
@hweeks Ok awesome. Let's wait for the checks to pass, then we will merge it in and see if it gets auto released.

**Comment by hweeks** [comment]
exciting!

**Comment by fishcharlie** [comment]
@hweeks I must have messed up the permissions...

**Comment by hweeks** [comment]
do you use your email for hangouts? it'll be quicker there to explain

**Comment by fishcharlie** [comment]
@hweeks What kinda GH_TOKEN is it looking for? I created a Personal access token with the following scopes:

`public_repo, repo:status, repo_deployment`

**Comment by fishcharlie** [comment]
@hweeks fishcharlie.code@gmail.com.

**Comment by hweeks** [comment]
i messaged you

**Pull request merged**
