### PR TITLE
Remove lodash and underscore

### PR DESCRIPTION
**Pull request by ro-savage**
A continuation from #194. **This removes both `lodash` and `underscore` completely.**

It is still compatible with Node v4+ but breaks compatibility with 0.12.

I've pulled in two much smaller libs that do specific tasks.

Removing `lodash` and `underscore` should take a decent chunk out of the `dynamoose` package size. 

Probably not important to most people but I am planning to use this on Lambda and the smaller the better.

**It makes sense if you are planning to do major changes and find `lodash/underscore` to be useful just to keep them in.**

### CODE REVIEW

**Comment by ro-savage** [comment]
Not sure why it failed most of the builds. 

Could be a timeout thing, because it passed in node5. But not really sure. Kind of weird.

**Comment by brandongoode** [comment]
I use it in lambda too and think removing lodash and underscore is a good; however, I going to hold off on breaking the 0.12 support until 0.9.

Could you update this PR to be for branch 0.9?

**Comment by ro-savage** [comment]
@brandongoode - Planning to do this on 0.9. Just haven't got around to it yet.

**Comment by fishcharlie** [comment]
@ro-savage @brandongoode, let's hold off on this until 1.0. I'm planning on making 0.9 non breaking. All breaking changes will hit on 1.0. If you have any objections please let me know, otherwise I'm going to set this milestone to 1.0 and plan on releasing it in 1.0.

**Comment by fishcharlie** [comment]
@ro-savage If you wanna get the conflicts solved and get this merged in that'd be awesome. As of `v1.0` we will be supporting Node.js 8+

**Comment by fishcharlie** [comment]
Closing due to #411

**Pull request closed without merging**
