### PR TITLE
feat(plugin): added item prop to event object passed to model:put put:called listener.

### PR DESCRIPTION
**Pull request by dolsem**
### Summary:
I've added an additional prop to the event object that is passed to plugin callbacks during `put:called` stage of  `model:put` event. The prop is `item` and it is equal to the model class instance that is being put into the database. I need this for the [optimistic locking plugin](https://github.com/dynamoosejs/dynamoose-plugin-ideas/issues/3), and I imagine it can be useful to other plugin creators as well. One use case is if we want to get updatedAt timestamp of the item being saved before the timestamp gets updated by Dynamoose.

### Other information:
As I was modifying the code I split `NewModel._emit()` call statements into multiple lines for better readability, and updated style of every statement so that they match. Hopefully you will find this tiny change useful. I also threw in extra tests for emit object properties for every stage of the `model:put` event.

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoosejs/dynamoose/blob/master/LICENSE.txt)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by dolsem** [comment]
@fishcharlie any update on this? Would be nice to get a review soon, since optimistic locking plugin depends on it, and optimistic locking is crucial in production.

**Comment by fishcharlie** [comment]
@dolsem Please keep in mind plugin support for Dynamoose is **very much** still in beta. @hweeks and I were talking about reworking the entire system to be more in line with Mongoose. But it was very much just initial discussions. Nothing concrete at all.

Other than that with that one review comment I had, I'll merge.

Sorry for the delay in looking over this, been super busy with other stuff.

**Comment by dolsem** [comment]
@fishcharlie okay, no problem.

**Comment by dolsem** [comment]
> There are a lot of cases where function calls are seperated onto two lines. Can we make this all one line.
> 
> Example:
> 
> ```js
> emitObject.should.have
> .propertyByPath('event', 'type').which.is.eql('model:put');
> ```
> 
> Should all be on one line.

I personally find code that does not have long lines more readable, but sure, if that's what you require.

**Comment by hweeks** [comment]
Looks like a good addition to functionality and well written. I’m cool with this post style cleanup.

**Comment by fishcharlie** [comment]
@dolsem In my opinion, it makes it harder to know where to split the line. I mean should you have split it before `which`? It'll never be consistent, and everyone will handle it slightly differently. Text wrap for text editors does the job of making it easier to read.

At the end of the day it's 100% personal opinion. I don't think we do multiline function calls anywhere else in the project, so I think the consistency argument has to win out in this case.

**Comment by fishcharlie** [comment]
@dolsem Do me a favor and when you fix those changes please be sure to tag me in a GitHub comment on this PR so I can re-review and merge.

**Comment by dolsem** [comment]
@fishcharlie should be all set

**Pull request merged**
