### PR TITLE
Added test for updating a model with  createdAt as rangeKey

### PR DESCRIPTION
**Pull request by soliveira-vouga**
This PR is for https://github.com/dynamoosejs/dynamoose/issues/382

### CODE REVIEW

**Comment by fishcharlie** [comment]
In the master branch we have added new schema's so `Cat10` and maybe `Cat11` need to be renamed to something higher. So when someone fixes this merge conflict it needs to be renamed throughout the entire PR.

**Comment by fishcharlie** [comment]
@soliveira-vouga I just wrote some basic logic for this. Tests are still failing tho. I feel like the logic I wrote should fix it by adding that range key. Are you sure that the only thing that we need to do to get this test to pass is add the range key? I haven't worked very much with range keys at all with DynamoDB, so I'm kinda a little bit in the dark here.

As well in order to merge this PR we still need to write tests for the `updatedAt` side of things, update the documentation to reflect this change, and update the TypeScript stuff.

**Comment by fishcharlie** [comment]
Closing this due to no recent activity. If this is still a problem or you have questions please feel free to comment again and we can try to help further.

**Comment by dolsem** [comment]
@fishcharlie here's something interesting. I've just tried the test on the master branch of Dynamoose. It passes, but it passes because 'createdAt' field name gets replaced with '[object Object]':
```js
{
  name: 'Fluffy',
  '[object Object]': 2019-11-09T20:28:10.981Z,
  age: 2,
  updatedAt: 2019-11-09T20:28:13.270Z,
  [Symbol(originalItem)]: {
    name: 'Fluffy',
    '[object Object]': '2019-11-09T20:28:10.981Z',
    age: 2,
    updatedAt: '2019-11-09T20:28:13.270Z'
  }
}
```
This issue can be avoided if you use a slightly different but equivalent schema:
```js
const Cat20 = dynamoose.model('Cat20', {
    name: {
      type: String,
      hashKey: true
    },
    createdAt: {
      type: Date,
      rangeKey: true,
    },
    age: {
      type: Number
    }
  }, { timestamps: true });
```
Test fails with this schema because of 2 different issues. One of them is caused by the same code that causes #607, and so it should get fixed by #689. The other one is the original issue - #382, looks like it's still there.

**Pull request closed without merging**
